title: Blog pessoal de Athos Bonner
description: > # this means to ignore newlines until "baseurl:"
  Bem vindo ao blog pessoal de Athos Bonner 
permalink: ':title/'
baseurl: "/athosbonner.github.io" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Athos Bonner # add your name
author-img: athosbonner.jpg # add your photo
about-author: Meu nome é Athos Bonner. Sou desenvoldedor de software e nas horas vagas escrevo, assisto séries, estudo, leio livros sobre biografias e o mais importante, corro de 3 a 10km. # add description
social-twitter: athosbonner # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: athosbonner # add your Github handle
social-linkedin: athos-bonner-28893441 # add your Linkedin handle
social-email: athos.sti@hotmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
